### ISSUE TITLE
[Progress Tracker]: University of Pittsburgh Medical Center

### ISSUE THREAD

**Issue by kzollove** [bridge2ai/StandardsModule#1]
### Data Contributing Site

University of Pittsburgh Medical Center

### Site Main Contact

Gilles Clermont

### ETL Representatives

Dan Ricketts

### Site Classification

Did not start with OMOP instance

### Data Classification Type?

- [ ] EHR Data
- [ ] Flowsheets
- [ ] Waveform Data
- [ ] Image Data

### Data Submission

- [ ] Has data been submitted?

### ETL Completion

- [ ] Has ETL been completed?

### Data Quality Dashboard (DQD) Execution

- [ ] Has Data Quality Dashboard (DQD) been run on your OMOP instance?

### Data Quality Dashboard (DQD) Submission

- [ ] Have the Data Quality Dashboard (DQD) results been submitted?

### Achilles Execution

- [ ] Has Achilles been run on your OMOP instance?

### Achilles Submission

- [ ] Have the Achilles results been submitted?

### Flowsheet data

- [ ] Has flowsheet data been identified?
- [ ] Has flowsheet format been identified?
- [ ] Has site begun mapping process?
- [ ] Has Standards Module reviewed flowsheet mappings?
