### ISSUE TITLE
[Progress Tracker] University of Pittsburgh Medical Center (more simple)

### ISSUE THREAD

**Issue by kzollove** [bridge2ai/StandardsModule#9]
### Data Contributing Site

University of Pittsburgh Medical Center

### Site Main Contact

Gilles Clermont

### ETL Representatives

Dan Ricketts

### Site Classification

Did not start with OMOP instance

### Data Classification Type?

- [ ] EHR Data
- [ ] Flowsheets
- [ ] Waveform Data
- [ ] Image Data

### Site TODO:

- [ ] Has data been submitted?
- [ ] Has ETL been completed?
- [ ] Has Data Quality Dashboard (DQD) been run on your OMOP instance?
- [ ] Have the Data Quality Dashboard (DQD) results been submitted?
- [ ] Has Achilles been run on your OMOP instance?
- [ ] Have the Achilles results been submitted?
- [ ] Has flowsheet data been identified?
- [ ] Has flowsheet format been identified?
- [ ] Has site begun mapping process?
- [ ] Has Standards Module reviewed flowsheet mappings?
